AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Controllers/AdminAuthController.cs
using AcunMedyaFestavaLive.Areas.Admin.Models;
using AcunMedyaFestavaLive.Entities;

using System.Linq;
using System.Web.Mvc;

namespace AcunMedyaFestavaLive.Areas.Admin.Controllers
{
    public class AdminAuthController : Controller
    {
        private readonly Context context = new Context();

        [HttpGet]
        public ActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignIn(AdminLoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var admin = context.admins.SingleOrDefault(a => a.Username == model.Username && a.Password == model.Password);

                if (admin != null)
                {
                    Session["AdminId"] = admin.AdminId;
                    Session["AdminUsername"] = admin.Username;

                    return RedirectToAction("CreateTicket", "AdminTicket");
                }

                ModelState.AddModelError("", "Geçersiz kullanıcı adı veya şifre.");
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult SignOut()
        {
            Session.Clear();
            return RedirectToAction("SignIn");
        }
    }
}

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Controllers/UserController.cs
using AcunMedyaFestavaLive.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaFestavaLive.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        Context context = new Context();
        public ActionResult UserList()
        {
            var values = context.users.ToList();
            
            return View(values);
        }
        public ActionResult DeleteUser(int id)
        {
            var values = context.users.Find(id);
            context.users.Remove(values);
            context.SaveChanges();
            return RedirectToAction("UserList");
        }
    }
}

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Controllers/DefaultController.cs
using AcunMedyaFestavaLive.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaFestavaLive.Controllers
{
    public class DefaultController : Controller
    {
        Context context = new Context();
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialHeader()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
           
        {
            return PartialView();
        }
        public PartialViewResult PartialFeature()
        {
            return PartialView();
        }
        public PartialViewResult PartialAbout()
        {
            return PartialView();
        }
        public PartialViewResult PartialMeetArtist()
        {
            var values = context.artists.OrderBy(x => x.ArtistId).Take(6).ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialEventSchedule()
        {
            return PartialView();
        }
        public PartialViewResult PartialTicket()
        {
            var values = context.tickets.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialContact()
        {
            return PartialView();
        }
        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }
    }
}

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/Index.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">
@Html.Action("PartialHead","Default") 


<body>

    <main>

        @Html.Action("PartialHeader", "Default")

        @Html.Action("PartialNavbar", "Default")

        @Html.Action("PartialFeature", "Default")

        @Html.Action("PartialAbout", "Default")

        @Html.Action("PartialMeetArtist", "Default")

        @Html.Action("PartialEventSchedule", "Default")

        @Html.Action("PartialTicket", "Default")

        @Html.Action("PartialContact", "Default")
    </main>

    @Html.Action("PartialFooter", "Default")

</body>

</html>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialAbout.cshtml
<section class="about-section section-padding" id="section_2">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 col-12 mb-4 mb-lg-0 d-flex align-items-center">
                <div class="services-info">
                    <h2 class="text-white mb-4">Festava 2024 Hakkında</h2>

                    <p class="text-white">
                        Festava 2024, müzik, eğlence ve unutulmaz anlarla dolu bir festivaldir.
                        Her yıl binlerce müzikseveri ağırlayan bu festivalde, en sevdiğiniz sanatçıları
                        ve müzik türlerini keşfedin. Festival alanında çeşitli etkinlikler ve aktiviteler
                        sizleri bekliyor.
                    </p>

                    <h6 class="text-white mt-4">Tüm Gece Parti</h6>

                    <p class="text-white">
                        Festava 2024'te, gece boyunca süren partilerle eğlencenin doruklarına çıkacaksınız.
                        Dans, müzik ve daha fazlası ile unutulmaz anlar yaşayacaksınız. Gecenin ritmini
                        hissedin ve yıldızların altında dans edin.
                    </p>

                </div>
            </div>

            <div class="col-lg-6 col-12">
                <div class="about-text-wrap">
                    <img src="~/Templates/FestavaLive-1.0.0/images/pexels-alexander-suhorucov-6457579.jpg" class="about-image img-fluid" alt="Festival Image">

                    <div class="about-text-info d-flex align-items-center mt-4">
                        <div>
                            <i class="about-text-icon bi-music-note"></i>
                        </div>

                        <div class="ms-4">
                            <h3 class="text-white">Müzik Dolu Anlar</h3>

                            <p class="text-white mb-0">Festava 2024'te unutulmaz bir müzik festivali deneyimi yaşayın.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialContact.cshtml
<section class="contact-section section-padding" id="section_6">
    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-12 mx-auto">
                <h2 class="text-center mb-4">Haydi Konuşalım?</h2>

                <nav class="d-flex justify-content-center">
                    <div class="nav nav-tabs align-items-baseline justify-content-center" id="nav-tab"
                         role="tablist">
                        <button class="nav-link active" id="nav-ContactForm-tab" data-bs-toggle="tab"
                                data-bs-target="#nav-ContactForm" type="button" role="tab"
                                aria-controls="nav-ContactForm" aria-selected="false">
                            <h5>İletişim Formu</h5>
                        </button>

                        <button class="nav-link" id="nav-ContactMap-tab" data-bs-toggle="tab"
                                data-bs-target="#nav-ContactMap" type="button" role="tab"
                                aria-controls="nav-ContactMap" aria-selected="false">
                            <h5>Google Haritalar</h5>
                        </button>
                    </div>
                </nav>

                <div class="tab-content shadow-lg mt-5" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-ContactForm" role="tabpanel"
                         aria-labelledby="nav-ContactForm-tab">
                        <form class="custom-form contact-form mb-5 mb-lg-0" action="#" method="post"
                              role="form">
                            <div class="contact-form-body">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-12">
                                        <input type="text" name="contact-name" id="contact-name"
                                               class="form-control" placeholder="Adınız Soyadınız " required>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-12">
                                        <input type="email" name="contact-email" id="contact-email"
                                               class="form-control"
                                               placeholder="Email adresiniz" required>
                                    </div>
                                </div>

                                <input type="text" name="contact-company" id="contact-company"
                                       class="form-control" placeholder="Konu" required>

                                <textarea name="contact-message" rows="3" class="form-control"
                                          id="contact-message" placeholder="Mesaj"></textarea>

                                <div class="col-lg-4 col-md-10 col-8 mx-auto">
                                    <button type="submit" class="form-control">Mesaj Gönder </button>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="tab-pane fade" id="nav-ContactMap" role="tabpanel"
                         aria-labelledby="nav-ContactMap-tab">
                        <iframe class="google-map"
                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d29974.469402870927!2d120.94861466021855!3d14.106066818082482!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x33bd777b1ab54c8f%3A0x6ecc514451ce2be8!2sTagaytay%2C%20Cavite%2C%20Philippines!5e1!3m2!1sen!2smy!4v1670344209509!5m2!1sen!2smy"
                                width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                                referrerpolicy="no-referrer-when-downgrade"></iframe>
                        <!-- You can easily copy the embed code from Google Maps -> Share -> Embed a map // -->
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialEventSchedule.cshtml
<section class="schedule-section section-padding" id="section_4">
    <div class="container">
        <div class="row">

            <div class="col-12 text-center">
                <h2 class="text-white mb-4">
                    Etkinlik Takvimi </h2>

                    <div class="table-responsive">
                        <table class="schedule-table table table-dark">
                            <thead>
                                <tr>
                                    <th scope="col">Zaman</th>

                                    <th scope="col">Cuma</th>

                                    <th scope="col">Cumartesi</th>

                                    <th scope="col">Pazar</th>

                                </tr>
                            </thead>

                            <tbody>
                                <tr>
                                    <th scope="row">Gün 1</th>

                                    <td class="table-background-image-wrap pop-background-image">
                                        <h3>Pop Performansı</h3>

                                        <p class="mb-2">19:00 - 21:00 PM</p>

                                        <p>By Adele</p>

                                        <div class="section-overlay"></div>
                                    </td>

                                    <td style="background-color: #F3DCD4"></td>

                                    <td class="table-background-image-wrap rock-background-image">
                                        <h3>Rock Performansı</h3>

                                        <p class="mb-2">19:00 - 21:00 PM</p>

                                        <p>By Rihana</p>

                                        <div class="section-overlay"></div>
                                    </td>
                                </tr>

                                <tr>
                                    <th scope="row">Gün 2</th>

                                    <td style="background-color: #ECC9C7"></td>

                                    <td>
                                        <h3>Rap Performansı </h3>

                                        <p class="mb-2">20:30 - 22:30 PM</p>

                                        <p>Travis Scoot</p>
                                    </td>

                                    <td style="background-color: #D9E3DA"></td>
                                </tr>

                                <tr>
                                    <th scope="row">Gün 3</th>

                                    <td class="table-background-image-wrap country-background-image">
                                        <h3>Dj Performansı </h3>

                                        <p class="mb-2">16:30 - 17:30 PM</p>

                                        <p>By Rihana</p>

                                        <div class="section-overlay"></div>
                                    </td>

                                    <td style="background-color: #D1CFC0"></td>

                                    <td>
                                        <h3>Serbest Zaman </h3>

                                        <p class="mb-2">16:00 - 18:00 PM</p>

                                        <p>By Members</p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>
</section>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialFeature.cshtml
<section class="hero-section" id="section_1">
    <div class="section-overlay"></div>

    <div class="container d-flex justify-content-center align-items-center">
        <div class="row">

            <div class="col-12 mt-auto mb-5 text-center">
                <small>Festava Live Gururla Yılın En Büyük Konser Etkinliğini Sunar</small>

                <h1 class="text-white mb-5">Yılın En Büyük Konserleri</h1>

                <a class="btn custom-btn smoothscroll" href="#section_2">Hemen Bilet Al</a>
            </div>

            <div class="col-lg-12 col-12 mt-auto d-flex flex-column flex-lg-row text-center">
                <div class="date-wrap">
                    <h5 class="text-white">
                        <i class="custom-icon bi-clock me-2"></i>
                        10 - 14<sup>th</sup>, Agustos 2024
                    </h5>
                </div>

                <div class="location-wrap mx-auto py-3 py-lg-0">
                    <h5 class="text-white">
                        <i class="custom-icon bi-geo-alt me-2"></i>
                        Küçük Çiftlik Park, Harbiye İstanbul
                    </h5>
                </div>

                <div class="social-share">
                    <ul class="social-icon d-flex align-items-center justify-content-center">
                        <span class="text-white me-3">Share:</span>

                        <li class="social-icon-item">
                            <a href="#" class="social-icon-link">
                                <span class="bi-facebook"></span>
                            </a>
                        </li>

                        <li class="social-icon-item">
                            <a href="#" class="social-icon-link">
                                <span class="bi-twitter"></span>
                            </a>
                        </li>

                        <li class="social-icon-item">
                            <a href="#" class="social-icon-link">
                                <span class="bi-instagram"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="video-wrap">
        <video autoplay="" loop="" muted="" class="custom-video" poster="">
            <source src="~/Templates/FestavaLive-1.0.0/video/pexels-2022395.mp4" type="video/mp4">

            Your browser does not support the video tag.
        </video>
    </div>
</section>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialFooter.cshtml
<footer class="site-footer">
    <div class="site-footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-6 col-12">
                    <h2 class="text-white mb-lg-0">Festava Live</h2>
                </div>

                <div class="col-lg-6 col-12 d-flex justify-content-lg-end align-items-center">
                    <ul class="social-icon d-flex justify-content-lg-end">
                        <li class="social-icon-item">
                            <a href="#" class="social-icon-link">
                                <span class="bi-twitter"></span>
                            </a>
                        </li>

                        <li class="social-icon-item">
                            <a href="#" class="social-icon-link">
                                <span class="bi-apple"></span>
                            </a>
                        </li>

                        <li class="social-icon-item">
                            <a href="#" class="social-icon-link">
                                <span class="bi-instagram"></span>
                            </a>
                        </li>

                        <li class="social-icon-item">
                            <a href="#" class="social-icon-link">
                                <span class="bi-youtube"></span>
                            </a>
                        </li>

                        <li class="social-icon-item">
                            <a href="#" class="social-icon-link">
                                <span class="bi-pinterest"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">

            <div class="col-lg-6 col-12 mb-4 pb-2">
                <h5 class="site-footer-title mb-3">Linkler</h5>

                <ul class="site-footer-links">
                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Anasayfa</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Hakkımızda</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Sanatçılar</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Takvin</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Biletler</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">İletişim</a>
                    </li>
                </ul>
            </div>

            <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                <h5 class="site-footer-title mb-3">Bir sorunuz mu var ?</h5>

                <p class="text-white d-flex mb-1">
                    <a href="tel: 090-080-0760" class="site-footer-link">
                       0554 125 8381
                    </a>
                </p>

                <p class="text-white d-flex">
                    <a href="mailto:hello@company.com" class="site-footer-link">
                        ipeknr12@company.com
                    </a>
                </p>
            </div>

            <div class="col-lg-3 col-md-6 col-11 mb-4 mb-lg-0 mb-md-0">
                <h5 class="site-footer-title mb-3">Lokasyon</h5>

                <p class="text-white d-flex mt-3 mb-2">
                    Küçükçiftlik Park ,Beşiktaş İstanbul 
                </p>

                <a class="link-fx-1 color-contrast-higher mt-3" href="#">
                    <span>Haritalar </span>
                    <svg class="icon" viewBox="0 0 32 32" aria-hidden="true">
                        <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">
                            <circle cx="16" cy="16" r="15.5"></circle>
                            <line x1="10" y1="18" x2="16" y2="12"></line>
                            <line x1="16" y1="12" x2="22" y2="18"></line>
                        </g>
                    </svg>
                </a>
            </div>
        </div>
    </div>

    <div class="site-footer-bottom">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-12 mt-5">
                    <p class="copyright-text">Copyright © 2036 Festava Live Company</p>
                   
                </div>

                <div class="col-lg-8 col-12 mt-lg-5">
                    <ul class="site-footer-links">
                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Şartlar &amp; Koşullar</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Gizlilik Politikası </a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Geri Bildirimleriniz </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- JAVASCRIPT FILES -->
<script src="~/Templates/FestavaLive-1.0.0/js/jquery.min.js"></script>
<script src="~/Templates/FestavaLive-1.0.0/js/bootstrap.min.js"></script>
<script src="~/Templates/FestavaLive-1.0.0/js/jquery.sticky.js"></script>
<script src="~/Templates/FestavaLive-1.0.0/js/click-scroll.js"></script>
<script src="~/Templates/FestavaLive-1.0.0/js/custom.js"></script>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialHead.cshtml
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>AcunMedya Akademi Festival Projesi</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;400;700&display=swap" rel="stylesheet">

    <link href="~/Templates/FestavaLive-1.0.0/css/bootstrap.min.css" rel="stylesheet">

    <link href="~/Templates/FestavaLive-1.0.0/css/bootstrap-icons.css" rel="stylesheet">

    <link href="~/Templates/FestavaLive-1.0.0/css/templatemo-festava-live.css" rel="stylesheet">

    <!--

    TemplateMo 583 Festava Live

    https://templatemo.com/tm-583-festava-live

    -->
</head>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialHeader.cshtml
<header class="site-header">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12 d-flex flex-wrap">
                <p class="d-flex me-4 mb-0">
                    <i class="bi-person custom-icon me-2"></i>
                    <strong class="text-dark">Acun Medya Akademi Müzik Festivali 2024'e Hoşgeldinizzz!</strong>
                </p>
            </div>

        </div>
    </div>
</header>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialMeetArtist.cshtml
@model List<AcunMedyaFestavaLive.Entities.Artist>

<section class="artists-section section-padding" id="section_3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <h2 class="mb-4">Etkinlik Sanatçılarımız</h2>
            </div>

            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-6 col-12 mb-4">
                    <div class="artists-thumb">
                        <div class="artists-image-wrap">
                            <img src="@item.ImageUrl"
                                 class="artists-image img-fluid">
                        </div>

                        <div class="artists-hover">
                            <p>
                                <strong>Ad Soyad:</strong>
                                @item.NameSurname
                            </p>

                            <p>
                                <strong>Etkinlik Saati:</strong>
                                @item.Date
                            </p>

                            <p>
                                <strong>Müzik Türü:</strong>
                                @item.Description
                            </p>

                            <hr>

                            <p class="mb-0">
                                <strong>Etkinlik Açıklama:</strong>
                                @item.Description2
                            </p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

<style>
    .artists-thumb {
        border: 1px solid #ddd;
        border-radius: 5px;
        overflow: hidden;
    }

    .artists-hover {
        padding: 15px;
      
        border-top: 1px solid #f0ad4e;
    }
</style>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialNavbar.cshtml
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a href="@Url.Action("SignIn", "AdminAuth", new { area = "Admin" })" class="navbar-brand">
            Festava Live
        </a>


        <a href="@Url.Action("Login", "User", new { area = "Member" })" class="btn custom-btn d-lg-none ms-auto me-4">Bilet Al</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav align-items-lg-center ms-auto me-lg-5">
                <li class="nav-item">
                    <a class="nav-link click-scroll" href="#section_1">AnaSayfa</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="#section_2">Hakkımızda</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="#section_3">Sanatçılar</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="#section_4">Takvim</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="#section_5">Biletler</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="#section_6">İletişim</a>
                </li>
            </ul>

            <a href="@Url.Action("Login", "User", new { area = "Member" })" class="btn custom-btn d-lg-block d-none">Bilet Al</a>

        </div>
    </div>
</nav>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Views/Default/PartialTicket.cshtml
@model List<AcunMedyaFestavaLive.Entities.Ticket>

<section class="pricing-section section-padding section-bg" id="section_5">
    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-12 mx-auto">
                <h2 class="text-center mb-4">Bilet Seçenekleri</h2>
            </div>

            @foreach (var item in Model)
            {
                <div class="col-lg-6 col-12 mt-4 mt-lg-0">
                    <div class="pricing-thumb">
                        <div class="d-flex">
                            <div>
                                <h3><small>@item.Title</small> @item.Price ₺ </h3>

                                <p>@item.Description</p>
                            </div>
                        </div>

                        <ul class="pricing-list mt-3">
                            <li class="pricing-list-item">@item.TicketProperty1</li>

                            <li class="pricing-list-item">@item.TicketProperty2</li>

                            <li class="pricing-list-item">@item.TicketProperty3</li>

                            <li class="pricing-list-item">@item.TicketProperty4</li>

                            <li class="pricing-list-item">@item.TicketProperty5</li>

                            <li class="pricing-list-item">@item.TicketProperty6</li>
                        </ul>

                        <a class="link-fx-1 color-contrast-higher mt-4" href="ticket.html">
                            <span>Satın Al</span>
                            <svg class="icon" viewBox="0 0 32 32" aria-hidden="true">
                                <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">
                                    <circle cx="16" cy="16" r="15.5"></circle>
                                    <line x1="10" y1="18" x2="16" y2="12"></line>
                                    <line x1="16" y1="12" x2="22" y2="18"></line>
                                </g>
                            </svg>
                        </a>
                    </div>
                </div>
            }



        </div>
    </div>
</section>