AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Controllers/AdminLayoutController.cs
using AcunMedyaFestavaLive.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaFestavaLive.Areas.Admin.Controllers
{
    public class AdminLayoutController : Controller
    {
        Context context = new Context();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView("~/Areas/Admin/Views/AdminLayout/PartialHead.cshtml");
        }
        public PartialViewResult PartialSideBar()
        {
            return PartialView("~/Areas/Admin/Views/AdminLayout/PartialSideBar.cshtml");
        }
        public PartialViewResult PartialScript()
        {
            return PartialView("~/Areas/Admin/Views/AdminLayout/PartialScript.cshtml");
        }
        public PartialViewResult PartialLogoHeader()
        {
            return PartialView("~/Areas/Admin/Views/AdminLayout/PartialLogoHeader.cshtml");
        }
        public PartialViewResult PartialNavbarHeader()
        {
            return PartialView("~/Areas/Admin/Views/AdminLayout/PartialNavbarHeader.cshtml");
        }
    }
}

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Controllers/AdminTicketController.cs
using AcunMedyaFestavaLive.Entities;
using System.Linq;
using System.Web.Mvc;


namespace AcunMedyaFestavaLive.Areas.Admin.Controllers
    {
        public class AdminTicketController : Controller
        {
            Context context = new Context();

            public ActionResult TicketList()
            {
                var values = context.tickets.ToList();
                return View(values);
            }

            [HttpGet]
            public ActionResult CreateTicket()
            {
                return View();
            }

            [HttpPost]
            public ActionResult CreateTicket(Ticket ticket)
            {
                context.tickets.Add(ticket);
                context.SaveChanges();
                return RedirectToAction("TicketList");
            }

            public ActionResult DeleteTicket(int id)
            {
                var values = context.tickets.Find(id);
                context.tickets.Remove(values);
                context.SaveChanges();
                return RedirectToAction("TicketList");
            }

            [HttpGet]
            public ActionResult UpdateTicket(int id)
            {
                var value = context.tickets.Find(id);
                if (value == null)
                {
                    return HttpNotFound();
                }
                return View(value);
            }

        [HttpPost]
        public ActionResult UpdateTicket(int id, Ticket ticket)
        {
            var value = context.tickets.Find(id);
            if (value != null)
            {
                value.TicketProperty1 = ticket.TicketProperty1;
                value.TicketProperty2 = ticket.TicketProperty2;
                value.TicketProperty3 = ticket.TicketProperty3;
                value.TicketProperty4 = ticket.TicketProperty4;
                value.TicketProperty5 = ticket.TicketProperty5;
                value.TicketProperty6 = ticket.TicketProperty6;
                value.Price = ticket.Price;
                value.Description = ticket.Description;
                value.Title = ticket.Title;
                context.SaveChanges();
            }
            return RedirectToAction("TicketList");
        }


        public ActionResult TicketDetails(int id)
            {
                var value = context.tickets.Find(id);
                if (value == null)
                {
                    return HttpNotFound();
                }
                return View(value);
            }
        public ActionResult ActivateTicket(int id)
        {
            var ticket = context.tickets.Find(id);
            if (ticket != null)
            {
                ticket.Status = true; // Aktif yapma
                context.SaveChanges();
            }
            return RedirectToAction("TicketList");
        }

        public ActionResult DeactivateTicket(int id)
        {
            var ticket = context.tickets.Find(id);
            if (ticket != null)
            {
                ticket.Status = false; // Pasif yapma
                context.SaveChanges();
            }
            return RedirectToAction("TicketList");
        }

        public ActionResult ActiveTickets()
        {
            var values = context.tickets.Where(t => t.Status).ToList();
            return View(values);
        }
    }


    }

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Controllers/ArtistController.cs
using AcunMedyaFestavaLive.Entities;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace AcunMedyaFestavaLive.Areas.Admin.Controllers
{
    public class ArtistController : Controller
    {
        private Context context = new Context();

        public ActionResult List()
        {
            List<Artist> artists = context.artists.ToList();
            return View(artists);
        }

        [HttpGet]
        public ActionResult CreateArtist()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateArtist(Artist artist)
        {
            if (ModelState.IsValid)
            {
                context.artists.Add(artist);
                context.SaveChanges();
                return RedirectToAction("List");
            }
            return View(artist);
        }

        [HttpGet]
        public ActionResult UpdateArtist(int id)
        {
            Artist artist = context.artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        [HttpPost]
        public ActionResult UpdateArtist(Artist artist)
        {
            if (ModelState.IsValid)
            {
                var existingArtist = context.artists.Find(artist.ArtistId);
                if (existingArtist != null)
                {
                    existingArtist.NameSurname = artist.NameSurname;
                    existingArtist.Date = artist.Date;
                    existingArtist.Description = artist.Description;
                    existingArtist.Description2 = artist.Description2;
                    existingArtist.ImageUrl = artist.ImageUrl;
                    context.SaveChanges();
                    return RedirectToAction("List");
                }
            }
            return View(artist);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteArtist(int id)
        {
            var artist = context.artists.Find(id);
            if (artist != null)
            {
                context.artists.Remove(artist);
                context.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Controllers/UserController.cs
using AcunMedyaFestavaLive.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaFestavaLive.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        Context context = new Context();
        public ActionResult UserList()
        {
            var values = context.users.ToList();
            
            return View(values);
        }
        public ActionResult DeleteUser(int id)
        {
            var values = context.users.Find(id);
            context.users.Remove(values);
            context.SaveChanges();
            return RedirectToAction("UserList");
        }
    }
}

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Views/AdminLayout/PartialHead.cshtml
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Admin Panelid</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link rel="stylesheet" href="~/Templates/Ready-Bootstrap-Dashboard-master/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="~/Templates/Ready-Bootstrap-Dashboard-master/assets/css/ready.css">
    <link rel="stylesheet" href="~/Templates/Ready-Bootstrap-Dashboard-master/assets/css/demo.css">
</head>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Views/AdminLayout/PartialLogoHeader.cshtml
<div class="logo-header">
    <a href="~/Templates/Ready-Bootstrap-Dashboard-master/index.html" class="logo">
        Admin Paneli
    </a>
    <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <button class="topbar-toggler more"><i class="la la-ellipsis-v"></i></button>
</div>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Views/AdminLayout/PartialNavbarHeader.cshtml
<nav class="navbar navbar-header navbar-expand-lg">
    <div class="container-fluid">

        <form class="navbar-left navbar-form nav-search mr-md-3" action="">
            <div class="input-group">
                <input type="text" placeholder="Ara ..." class="form-control">
                <div class="input-group-append">
                    <span class="input-group-text">
                        <i class="la la-search search-icon"></i>
                    </span>
                </div>
            </div>
        </form>
        <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
            <li class="nav-item dropdown hidden-caret">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="la la-envelope"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item dropdown hidden-caret">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="la la-bell"></i>
                    <span class="notification">3</span>
                </a>
                <ul class="dropdown-menu notif-box" aria-labelledby="navbarDropdown">
                    <li>
                        <div class="dropdown-title">4 adet bildiriminiz var</div>
                    </li>
                    <li>
                        <div class="notif-center">
                            <a href="#">
                                <div class="notif-icon notif-primary"> <i class="la la-user-plus"></i> </div>
                                <div class="notif-content">
                                    <span class="block">
                                        New user registered
                                    </span>
                                    <span class="time">5 minutes ago</span>
                                </div>
                            </a>
                            <a href="#">
                                <div class="notif-icon notif-success"> <i class="la la-comment"></i> </div>
                                <div class="notif-content">
                                    <span class="block">
                                        Rahmad commented on Admin
                                    </span>
                                    <span class="time">12 minutes ago</span>
                                </div>
                            </a>
                            <a href="#">
                                <div class="notif-img">
                                    <img src="assets/img/profile2.jpg" alt="Img Profile">
                                </div>
                                <div class="notif-content">
                                    <span class="block">
                                        Reza send messages to you
                                    </span>
                                    <span class="time">12 minutes ago</span>
                                </div>
                            </a>
                            <a href="#">
                                <div class="notif-icon notif-danger"> <i class="la la-heart"></i> </div>
                                <div class="notif-content">
                                    <span class="block">
                                        Farrah liked Admin
                                    </span>
                                    <span class="time">17 minutes ago</span>
                                </div>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="see-all" href="javascript:void(0);"> <strong>Tüm Bildirimleri Gör  </strong> <i class="la la-angle-right"></i> </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false"> <img src="https://i.hizliresim.com/tv8744u.jpg" alt="user-img" width="36" class="img-circle"><span> Yetkili</span></span> </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <div class="user-box">
                            <div class="u-img"><img src="Ready-Bootstrap-Dashboard-masterassets/img/profile.jpg" alt="user"></div>
                            <div class="u-text">
                                <h4>İpek Öztürk</h4>
                                <p class="text-muted">hello@themekita.com</p><a href="profile.html" class="btn btn-rounded btn-danger btn-sm">Profili Gör </a>
                            </div>
                        </div>
                    </li>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#"><i class="ti-user"></i> My Profile</a>
                    <a class="dropdown-item" href="#"></i> My Balance</a>
                    <a class="dropdown-item" href="#"><i class="ti-email"></i> Inbox</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#"><i class="ti-settings"></i> Account Setting</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#"><i class="fa fa-power-off"></i> Logout</a>
                </ul>
                <!-- /.dropdown-user -->
            </li>
        </ul>
    </div>
</nav>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Views/AdminLayout/PartialScript.cshtml
<div class="modal fade" id="modalUpdate" tabindex="-1" role="dialog" aria-labelledby="modalUpdatePro" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h6 class="modal-title"><i class="la la-frown-o"></i> Under Development</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <p>Currently the pro version of the <b>Ready Dashboard</b> Bootstrap is in progress development</p>
                <p>
                    <b>We'll let you know when it's done</b>
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/core/popper.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/core/bootstrap.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/plugin/chartist/chartist.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/plugin/chartist/plugin/chartist-plugin-tooltip.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/plugin/jquery-mapael/jquery.mapael.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/plugin/jquery-mapael/maps/world_countries.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/plugin/chart-circle/circles.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/ready.min.js"></script>
<script src="~/Templates/Ready-Bootstrap-Dashboard-master/assets/js/demo.js"></script>

AcunMedyaFestavaLive/AcunMedyaFestavaLive/Areas/Admin/Views/AdminLayout/PartialSideBar.cshtml
<div class="sidebar">
    <div class="scrollbar-inner sidebar-wrapper">
        <div class="user">
            <div class="photo" >
                <img src="https://i.hizliresim.com/tv8744u.jpg">
            </div>
            <div class="info">
                <a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                    <span>
                        İpek Öztürk
                        <span class="user-level">Yetkili</span>
                        <span class="caret"></span>
                    </span>
                </a>
                <div class="clearfix"></div>

                <div class="collapse in" id="collapseExample" aria-expanded="true" style="">
                    <ul class="nav">
                        <li>
                            <a href="#profile">
                                <span class="link-collapse">My Profile</span>
                            </a>
                        </li>
                        <li>
                            <a href="#edit">
                                <span class="link-collapse">Edit Profile</span>
                            </a>
                        </li>
                        <li>
                            <a href="#settings">
                                <span class="link-collapse">Settings</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a href="/Default/Index">
                    <i class="la la-dashboard"></i>
                    <p>Siteye Git</p>
                    <span class="badge badge-count">5</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("CreateTicket", "AdminTicket", new { area = "Admin" })">
                    <i class="la la-table"></i>
                    <p>Bilet Ekle</p>
                    <span class="badge badge-count">14</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("TicketList", "AdminTicket", new { area = "Admin" })">
                    <i class="la la-table"></i>
                    <p>Bilet İşlemleri</p>
                    <span class="badge badge-count">14</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("ActiveTickets", "AdminTicket", new { area = "Admin" })">
                    <i class="la la-th"></i>
                    <p>Aktif Biletler</p>
                    <span class="badge badge-count">6</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="forms.html">
                    <i class="la la-keyboard-o"></i>
                    <p>Gelen Mesajlar</p>
                    <span class="badge badge-count">50</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("List", "Artist", new { area = "Admin" })">
                    <i class="la la-th"></i>
                    <p>Sanatçı İşlemleri</p>
                    <span class="badge badge-count">6</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("UserList", "User", new { area = "Admin" })">
                    <i class="la la-th"></i>
                    <p>Kullanıcılar</p>
                    <span class="badge badge-count">6</span>
                </a>
            </li>


        </ul>
    </div>
</div>